export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  brand: string;
  price: number;
  compareAt?: number;
  rating?: number;
  reviewCount?: number;
  stock: number;
  image: string;
  label?: string;
  description: string;
  createdAt?: string;
  isSellerAdded?: boolean;
};

// Preview catalog inspired by Kigali's grocery, food, and everyday-needs marketplace.
// All stock, prices, and seller names are example listings, not live store data.
export const seedProducts: Product[] = [
  {
    id: "p-01",
    slug: "fresh-market-greens-basket",
    name: "Fresh market greens basket",
    category: "Groceries",
    brand: "Kimironko Market",
    price: 6500,
    compareAt: 8000,
    stock: 12,
    image: "/catalog/market-produce.jpg",
    label: "Market fresh",
    description: "A colourful basket of seasonal greens and vegetables, selected for your everyday meals by a local market seller.",
  },
  {
    id: "p-02",
    slug: "sweet-yellow-bananas-1kg",
    name: "Sweet yellow bananas · 1 kg",
    category: "Groceries",
    brand: "Kimironko Market",
    price: 2500,
    compareAt: 3000,
    stock: 23,
    image: "/catalog/bananas.jpg",
    label: "A Kigali favourite",
    description: "Ripe, naturally sweet bananas for breakfast, lunchboxes, and the snack drawer. Sold by the kilogram.",
  },
  {
    id: "p-03",
    slug: "garden-avocado-tomato-box",
    name: "Avocado & tomato box",
    category: "Groceries",
    brand: "Kimironko Market",
    price: 4200,
    stock: 16,
    image: "/catalog/market-basket.jpg",
    label: "Fresh today",
    description: "A handy mix of ripe avocado, tomatoes, and seasonal produce for salads, toast, and family meals.",
  },
  {
    id: "p-04",
    slug: "coca-cola-original-500ml",
    name: "Coca-Cola Original · 500 ml",
    category: "Beverages & Spirits",
    brand: "City Drinks",
    price: 1500,
    stock: 28,
    image: "/catalog/cola.jpg",
    label: "Chilled favourite",
    description: "An ice-cold 500 ml bottle of Coca-Cola. Add a little refreshment to your next meal.",
  },
  {
    id: "p-05",
    slug: "vegetable-oil-1-litre",
    name: "Everyday vegetable oil · 1 L",
    category: "Groceries",
    brand: "Igihobe Supermarket",
    price: 4800,
    compareAt: 5400,
    stock: 9,
    image: "/catalog/cooking-oil.jpg",
    label: "Good value",
    description: "A kitchen staple for daily cooking, packed in a one-litre bottle from a trusted neighbourhood shop.",
  },
  {
    id: "p-06",
    slug: "crispy-chicken-shawarma-wrap",
    name: "Crispy chicken shawarma wrap",
    category: "Food",
    brand: "Urban Grill",
    price: 4500,
    compareAt: 5500,
    stock: 11,
    image: "/catalog/shawarma.jpg",
    label: "Ready to enjoy",
    description: "A generously filled chicken shawarma served with crisp fries and a side of dip. Prepared fresh by a local kitchen.",
  },
  {
    id: "p-07",
    slug: "double-cheese-burger-fries",
    name: "Double cheese burger & fries",
    category: "Food",
    brand: "Burger Bros",
    price: 7500,
    stock: 8,
    image: "/catalog/burgers.jpg",
    label: "Lunch favourite",
    description: "A double burger with cheese, lettuce, and golden fries. A satisfying pick for lunch or an easy dinner.",
  },
  {
    id: "p-08",
    slug: "grilled-chicken-and-fries",
    name: "Grilled chicken & fries",
    category: "Food",
    brand: "Urban Grill",
    price: 6500,
    stock: 14,
    image: "/catalog/grilled-meal.jpg",
    label: "Kitchen pick",
    description: "A freshly prepared chicken meal with fries and a tasty dip, packed and ready for delivery.",
  },
  {
    id: "p-09",
    slug: "shawarma-share-platter",
    name: "Shawarma share platter",
    category: "Food",
    brand: "Burger Bros",
    price: 9800,
    compareAt: 11500,
    stock: 6,
    image: "/catalog/shawarma-platter.jpg",
    label: "Share the good stuff",
    description: "A shareable platter with warm wraps, crunchy fries, and sauces for the table. Prepared fresh to order.",
  },
  {
    id: "p-10",
    slug: "home-cleaning-essentials-set",
    name: "Home cleaning essentials set",
    category: "Essentials",
    brand: "Tamba Supermarket",
    price: 12500,
    compareAt: 15000,
    stock: 5,
    image: "/catalog/cleaning-products.jpg",
    label: "Home essentials",
    description: "A useful mix of everyday home-care essentials to help keep your kitchen and living space feeling fresh.",
  },
  {
    id: "p-11",
    slug: "market-mix-family-vegetables",
    name: "Family mix of fresh vegetables",
    category: "Groceries",
    brand: "Kimironko Market",
    price: 5800,
    stock: 18,
    image: "/catalog/market-stall.jpg",
    label: "Picked this morning",
    description: "A family-size mix of market vegetables, packed with the day's freshest seasonal picks.",
  },
  {
    id: "p-12",
    slug: "local-market-fruit-and-greens",
    name: "Local market fruit & greens",
    category: "Groceries",
    brand: "Kimironko Market",
    price: 7200,
    compareAt: 8500,
    stock: 7,
    image: "/catalog/market-basket.jpg",
    label: "Save on the basket",
    description: "A convenient produce bundle with fruit and greens for a few easy meals at home.",
  },
  {
    id: "p-13",
    slug: "fresh-coffee-for-slow-mornings",
    name: "Fresh coffee for slow mornings",
    category: "Beverages & Spirits",
    brand: "Kivu Roasters",
    price: 6800,
    stock: 10,
    image: "/catalog/coffee.jpg",
    label: "Locally loved",
    description: "A smooth, warming coffee for slow mornings and a proper pause in the middle of the day.",
  },
  {
    id: "p-14",
    slug: "daily-care-skincare-set",
    name: "Daily care skincare set",
    category: "Beauty & Personal Care",
    brand: "Mira Botanics",
    price: 9500,
    stock: 6,
    image: "/catalog/skincare.jpg",
    label: "Everyday care",
    description: "A simple self-care set with everyday skincare essentials to keep close by the sink or in your travel bag.",
  },
  {
    id: "p-15",
    slug: "mid-range-smartphone-128gb",
    name: "Mid-range smartphone · 128 GB",
    category: "Electronics",
    brand: "Kigali Tech House",
    price: 289000,
    compareAt: 329000,
    rating: 4.7,
    reviewCount: 18,
    stock: 8,
    image: "/catalog/electronics-smartphone.jpg",
    label: "Tech pick",
    description: "A sample 128 GB smartphone listing with a bright display, capable camera, and all-day battery for everyday use.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-16",
    slug: "everyday-14-inch-laptop",
    name: "Everyday 14-inch laptop",
    category: "Electronics",
    brand: "Kigali Tech House",
    price: 685000,
    rating: 4.8,
    reviewCount: 12,
    stock: 4,
    image: "/catalog/electronics-laptop.jpg",
    label: "Work & study",
    description: "A lightweight laptop sample for everyday work, study, browsing, and video calls.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-17",
    slug: "wireless-earbuds-charging-case",
    name: "Wireless earbuds with charging case",
    category: "Electronics",
    brand: "Kigali Tech House",
    price: 29000,
    compareAt: 35000,
    rating: 4.6,
    reviewCount: 23,
    stock: 20,
    image: "/catalog/electronics-earbuds.jpg",
    label: "Easy listening",
    description: "Compact wireless earbuds with a pocket-sized charging case, ready for commutes, calls, and playlists.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-18",
    slug: "smart-watch-silicone-band",
    name: "Smart watch with silicone band",
    category: "Electronics",
    brand: "Kigali Tech House",
    price: 75000,
    rating: 4.5,
    reviewCount: 9,
    stock: 13,
    image: "/catalog/electronics-watch.jpg",
    label: "New arrival",
    description: "A sample smartwatch with a comfortable band, activity tracking, and an easy-to-read touch display.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-19",
    slug: "portable-bluetooth-speaker",
    name: "Portable Bluetooth speaker",
    category: "Electronics",
    brand: "Kigali Tech House",
    price: 48000,
    rating: 4.4,
    reviewCount: 11,
    stock: 9,
    image: "/catalog/electronics-speaker.jpg",
    label: "Small but mighty",
    description: "A compact portable speaker sample for music at home, on a picnic, or while travelling.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-20",
    slug: "10-inch-wifi-tablet-64gb",
    name: "10-inch Wi-Fi tablet · 64 GB",
    category: "Electronics",
    brand: "Kigali Tech House",
    price: 255000,
    compareAt: 279000,
    rating: 4.6,
    reviewCount: 7,
    stock: 6,
    image: "/catalog/electronics-tablet.jpg",
    label: "Study essential",
    description: "A sample 10-inch tablet with 64 GB of storage for reading, streaming, and everyday study.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-21",
    slug: "cream-canvas-everyday-sneakers",
    name: "Cream canvas everyday sneakers",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 28000,
    rating: 4.8,
    reviewCount: 16,
    stock: 15,
    image: "/catalog/shoes-canvas-sneakers.jpg",
    label: "Everyday favourite",
    description: "Light, easy-to-pair canvas sneakers with cushioned soles for everyday walks around town.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-22",
    slug: "charcoal-lime-running-shoes",
    name: "Charcoal running shoes",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 44000,
    compareAt: 52000,
    rating: 4.7,
    reviewCount: 14,
    stock: 10,
    image: "/catalog/shoes-running.jpg",
    label: "Move comfortably",
    description: "Breathable mesh running shoes with a lightweight feel for exercise and busy days.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-23",
    slug: "classic-leather-loafers",
    name: "Classic leather loafers",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 56000,
    rating: 4.6,
    reviewCount: 8,
    stock: 7,
    image: "/catalog/shoes-loafers.jpg",
    label: "Smart casual",
    description: "Polished brown leather-look loafers with a timeless shape for workdays and special plans.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-24",
    slug: "tan-cross-strap-sandals",
    name: "Tan cross-strap sandals",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 24500,
    rating: 4.5,
    reviewCount: 10,
    stock: 17,
    image: "/catalog/shoes-sandals.jpg",
    label: "Warm-weather pick",
    description: "Easy flat sandals with soft tan straps and a comfortable sole for relaxed days.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-25",
    slug: "brown-leather-city-derby-shoes",
    name: "Brown leather city derby shoes",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 65000,
    compareAt: 72000,
    rating: 4.7,
    reviewCount: 6,
    stock: 5,
    image: "/catalog/shoes-brown-derby.jpg",
    label: "Made for occasions",
    description: "A smart pair of brown lace-up shoes for office outfits, celebrations, and polished everyday looks.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-26",
    slug: "classic-brown-oxford-shoes",
    name: "Classic brown oxford shoes",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 79000,
    rating: 4.6,
    reviewCount: 5,
    stock: 4,
    image: "/catalog/shoes-oxford.jpg",
    label: "Occasion ready",
    description: "Classic lace-up leather-look shoes with a clean profile for formal and business outfits.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-27",
    slug: "grip-sole-trail-walking-shoes",
    name: "Grip-sole trail walking shoes",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 55000,
    rating: 4.5,
    reviewCount: 8,
    stock: 9,
    image: "/catalog/shoes-trail-runner.jpg",
    label: "Weekend explorer",
    description: "Sturdy walking shoes with textured soles for park paths, weekend hikes, and outdoor exploring.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-28",
    slug: "brown-casual-boat-shoes",
    name: "Brown casual boat shoes",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 49000,
    rating: 4.4,
    reviewCount: 5,
    stock: 6,
    image: "/catalog/shoes-boat-shoes.jpg",
    label: "Relaxed classic",
    description: "Casual brown lace-up shoes with a light sole, suited to easy weekends and smart-casual outfits.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-29",
    slug: "black-streetwear-sneakers",
    name: "Black streetwear sneakers",
    category: "Shoes",
    brand: "Kigali Steps",
    price: 41000,
    compareAt: 47000,
    rating: 4.5,
    reviewCount: 12,
    stock: 11,
    image: "/catalog/shoes-black-sneakers.jpg",
    label: "Easy everyday style",
    description: "Modern black sneakers with a cushioned sole and understated design for everyday wear.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-30",
    slug: "kitenge-print-wrap-dress",
    name: "Kitenge print wrap dress",
    category: "Clothing",
    brand: "Imena Style",
    price: 62000,
    rating: 4.9,
    reviewCount: 15,
    stock: 6,
    image: "/catalog/clothing-kitenge-dress.jpg",
    label: "Local style",
    description: "A colourful African-print wrap dress sample with a flattering waist tie, made for celebrations and everyday style.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-31",
    slug: "neutral-everyday-outfit-set",
    name: "Neutral everyday outfit set",
    category: "Clothing",
    brand: "Imena Style",
    price: 38000,
    rating: 4.6,
    reviewCount: 9,
    stock: 12,
    image: "/catalog/clothing-casual-outfit.jpg",
    label: "Easy to wear",
    description: "A relaxed shirt-and-denim outfit sample for casual days, with a simple neutral colour palette.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-32",
    slug: "dark-casual-streetwear-set",
    name: "Dark casual streetwear set",
    category: "Clothing",
    brand: "Imena Style",
    price: 52000,
    compareAt: 59000,
    rating: 4.7,
    reviewCount: 7,
    stock: 8,
    image: "/catalog/clothing-streetwear-set.jpg",
    label: "Weekend edit",
    description: "A coordinated casual outfit sample with dark denim and a simple black top for relaxed weekends.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-33",
    slug: "blue-striped-weekend-top-set",
    name: "Blue striped weekend top set",
    category: "Clothing",
    brand: "Imena Style",
    price: 29000,
    rating: 4.5,
    reviewCount: 6,
    stock: 10,
    image: "/catalog/clothing-striped-outfit.jpg",
    label: "Fresh stripes",
    description: "A breezy striped top paired with denim in this sample casual outfit listing.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-34",
    slug: "classic-denim-weekend-look",
    name: "Classic denim weekend look",
    category: "Clothing",
    brand: "Imena Style",
    price: 42000,
    rating: 4.6,
    reviewCount: 8,
    stock: 9,
    image: "/catalog/clothing-denim-outfit.jpg",
    label: "Denim days",
    description: "An easy denim-based clothing bundle sample styled for relaxed weekends and everyday errands.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-35",
    slug: "african-print-occasion-outfit",
    name: "African-print occasion outfit",
    category: "Clothing",
    brand: "Imena Style",
    price: 74000,
    rating: 4.8,
    reviewCount: 11,
    stock: 5,
    image: "/catalog/clothing-african-print-collection.jpg",
    label: "Colourful occasion wear",
    description: "A vibrant African-print fashion sample inspired by the joyful colours and patterns worn across the region.",
    createdAt: "2026-10-03",
  },
  {
    id: "p-36",
    slug: "soft-knit-and-denim-outfit",
    name: "Soft knit and denim outfit",
    category: "Clothing",
    brand: "Imena Style",
    price: 48000,
    compareAt: 55000,
    rating: 4.4,
    reviewCount: 4,
    stock: 7,
    image: "/catalog/clothing-knit-denim-flatlay.jpg",
    label: "Layer up",
    description: "A soft knit-and-denim outfit sample with an easy layered look for cooler mornings and evenings.",
    createdAt: "2026-10-03",
  },
];

export const categories = [
  "Groceries",
  "Beverages & Spirits",
  "Beauty & Personal Care",
  "Food",
  "Essentials",
  "Home & Kitchen",
  "Electronics",
  "Toys & Games",
  "Sports & Outdoors",
  "Shoes",
  "Clothing",
  "Gifts & Occasions",
];

export function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
